services:
  - type: web
    name: rameswaramdryfish-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
