const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/images', express.static('public/images'));

const products = [
  { id: "1", name: "Rameswaram Premium Nethili Karuvadu", nameTamil: "நெத்திலி கருவட", slug: "nethili-karuvadu", description: "Experience the authentic taste of the coast with Rameswaram Dry Fish's Premium Nethili Karuvadu. Our dried anchovies are handpicked and processed using traditional sun-drying methods, ensuring they retain their natural flavor and nutritional value. The 'Nethili' variety is beloved in Tamil cuisine for its small size and intense, savory flavor, making it a perfect addition to many classic South Indian recipes.\n\nOur product is processed under stringent quality standards. We use only fresh fish and natural sea salt, with absolutely no added chemicals or colorings.\n\nAUTHENTIC RAMESWARAM CATCH: Sourced directly from the clean coastal waters of Rameswaram, ensuring authentic flavor and premium quality.\n100% NATURAL & SUN-DRIED: Our Nethili Karuvadu is cleaned thoroughly and dried under strict hygienic conditions. No chemicals or artificial preservatives are added.\nRESEALABLE FRESHNESS: Comes in an easy-open, resealable standing pouch to maintain quality and aroma after opening.\nNUTRITIOUS & FLAVORFUL: A rich source of protein and essential minerals. These dried anchovies add a profound umami flavor to traditional dishes.\nVERSATILE KITCHEN STAPLE: Perfect for making crispy Nethili fry, spicy Thokku (dried fish masala), or traditional Meen Kuzhambu (fish curry).\n\nPreparation Instructions:\nBefore cooking, wash the dried fish 2-3 times with lukewarm water to remove excess salt and any surface particles. Pat dry before frying or adding to curries.\n\nStorage Instructions:\nStore in a cool, dry place. Once opened, transfer to an airtight container and, for maximum freshness, store in the refrigerator.\n\nManufacturer: Rameswaram Dry Fish, Chennai, Tamil Nadu, India.\nFSSAI Lic. No. 12421021002138", shortDesc: "Sun-dried anchovies - 100% natural & hygienic", category: "Fish", images: ["http://10.0.2.2:4000/images/nethili-1.jpg", "http://10.0.2.2:4000/images/nethili-2.jpg", "http://10.0.2.2:4000/images/nethili-3.jpg", "http://10.0.2.2:4000/images/nethili-4.jpg"], skus: [{ id: "1-80g", weight: "80g", price: 6500, stock: 50 }, { id: "1-160g", weight: "160g", price: 12000, stock: 30 }, { id: "1-240g", weight: "240g", price: 18000, stock: 20 }, { id: "1-500g", weight: "500g", price: 36000, stock: 15 }], tags: ["bestseller"], isFeatured: true, isBestseller: true, rating: 4.8, reviewCount: 124 },
  { id: "2", name: "Premium Podi Nethili Karuvadu", nameTamil: "பொடி நெத்திலி கருவட", slug: "podi-nethili-karuvadu", description: "Bring the authentic taste of the coast straight to your kitchen with Rameswaram Dry Fish - Podi Nethili Karuvadu. Sourced directly from small boats to guarantee the freshest catch, our small anchovies are cleaned and sun-dried under strict hygienic conditions. Whether you are making a spicy Nethili Karuvadu Thokku, a crispy fry, or a rich traditional kuzhambu, these bite-sized dried fish deliver a punch of rich, savory umami flavor to every meal.\n\nWhy Choose Our Podi Nethili?\n100% Natural: Just premium fish and sea salt. Absolutely no added chemicals or artificial preservatives.\n\nReady to Cook: Carefully cleaned and prepared. Just wash with lukewarm water and it is ready for your pan.\n\nPremium Quality Packaging: Packed in an easy-open, resealable pouch with a transparent window so you can see the quality for yourself.\n\nIncredible Value: Authentic coastal taste for just ₹65.\n\nIngredients: Fresh Fish, Sea Salt.\nStorage Instructions: Store in a cool, dry place. Keep in an airtight container once opened. Keep in the refrigerator to maintain ultimate freshness.", shortDesc: "Sun-dried small anchovies - 100% natural", category: "Fish", images: ["http://10.0.2.2:4000/images/podi-nethili-1.png", "http://10.0.2.2:4000/images/podi-nethili-2.png", "http://10.0.2.2:4000/images/podi-nethili-3.png", "http://10.0.2.2:4000/images/podi-nethili-4.jpg"], skus: [{ id: "2-75g", weight: "75g", price: 6500, stock: 40 }, { id: "2-150g", weight: "150g", price: 12000, stock: 35 }, { id: "2-225g", weight: "225g", price: 18000, stock: 25 }, { id: "2-500g", weight: "500g", price: 36000, stock: 20 }], tags: ["bestseller"], isFeatured: true, isBestseller: true, rating: 4.9, reviewCount: 156 },
  { id: "3", name: "Kilicha Fish Karuvadu", nameTamil: "கிழிச்ச மீன் கருவட", slug: "kilicha-fish-karuvadu", description: "Rameswaram Kilicha Karuvadu – Simply Fresh, Purely Dried.\n\nCraving the authentic taste of the coast? Our Kilicha Karuvadu is 100% natural, hygienic, and packed with traditional flavor.\n\nFreshly Sourced: Brought in daily by local small boats.\nPurely Sun-Dried: No chemicals, no additives, just pure fish and sea salt.\nReady-to-Cook: Cleaned with care so you can cook with confidence.\nSustainable: Supporting traditional fishing communities with every pack.", shortDesc: "Cleaned dried fish chunks", category: "Fish", images: ["http://10.0.2.2:4000/images/kilicha-6.png", "http://10.0.2.2:4000/images/kilicha-1.jpg", "http://10.0.2.2:4000/images/kilicha-2.jpg", "http://10.0.2.2:4000/images/kilicha-3.jpg", "http://10.0.2.2:4000/images/kilicha-4.jpg", "http://10.0.2.2:4000/images/kilicha-5.jpg"], skus: [{ id: "3-160g", weight: "160g", price: 6500, stock: 40 }, { id: "3-320g", weight: "320g", price: 12000, stock: 30 }, { id: "3-480g", weight: "480g", price: 18000, stock: 20 }, { id: "3-1kg", weight: "1kg", price: 36000, stock: 10 }], tags: ["bestseller"], isFeatured: true, isBestseller: true, rating: 4.7, reviewCount: 89 },
  { id: "4", name: "Premium Sennakuni Karuvadu", nameTamil: "சென்னா குனி கருவட", slug: "senna-kuni-karuvadu", description: "Premium Sennakuni - authentic coastal delight. Intense, savory crunch perfect for thokku, fry, or adding to vegetable curries.", shortDesc: "Dried shrimp - authentic coastal", category: "Prawns", images: ["http://10.0.2.2:4000/images/senna-kuni-1.png", "http://10.0.2.2:4000/images/senna-kuni-2.jpg", "http://10.0.2.2:4000/images/senna-kuni-3.jpg", "http://10.0.2.2:4000/images/senna-kuni-4.jpg"], skus: [{ id: "4-90g", weight: "90g", price: 6500, stock: 35 }, { id: "4-180g", weight: "180g", price: 12000, stock: 25 }, { id: "4-270g", weight: "270g", price: 18000, stock: 18 }, { id: "4-550g", weight: "550g", price: 36000, stock: 12 }], tags: ["bestseller"], isFeatured: false, isBestseller: true, rating: 4.8, reviewCount: 78 },
  { id: "5", name: "Premium Vaalai Karuvadu", nameTamil: "வாலை கருவட", slug: "vaalai-karuvadu", description: "Experience the authentic, traditional taste of coastal Tamil Nadu with our premium Vaalai Karuvadu (Ribbon Fish). Sourced directly from local small-boat fishermen, our Ribbon Fish is processed under strict hygienic conditions to ensure you receive only the finest quality.\n\nEvery batch is meticulously cleaned and sun-dried to lock in that deep, savory umami flavor that food lovers cherish. Whether you are planning to prepare a spicy, aromatic Karuvadu Kuzhambu (dried fish curry) or a crispy Karuvadu Varuval (fry), our premium Vaalai Karuvadu provides the perfect texture and bold taste to elevate your home-cooked meals.\n\nWhy choose our Vaalai Karuvadu?\n100% Natural: No added chemicals or preservatives. Just pure, sun-dried goodness.\nSustainably Sourced: We support local small-scale fishers for the freshest catch.\nHygienically Processed: Cleaned and dried in a controlled environment to ensure food safety.\nConvenient Packaging: Our easy-open, resealable pouch keeps your fish fresh for longer and makes storage effortless.\n\nCooking Tip: For the best results, wash the pieces gently in lukewarm water before cooking to achieve the perfect texture for your favorite recipes.\n\nNet Weight: 110g | Ingredients: Ribbon Fish (Vaalai), Sea Salt\nStorage: Keep in a cool, dry place. For extended freshness, store in an airtight container or refrigerate once opened.", shortDesc: "Sun-dried ribbon fish - 100% natural", category: "Fish", images: ["http://10.0.2.2:4000/images/vaalai-2.png", "http://10.0.2.2:4000/images/vaalai-1.png", "http://10.0.2.2:4000/images/vaalai-3.jpg", "http://10.0.2.2:4000/images/vaalai-4.jpg"], skus: [{ id: "5-110g", weight: "110g", price: 6500, stock: 45 }, { id: "5-220g", weight: "220g", price: 12000, stock: 30 }, { id: "5-330g", weight: "330g", price: 18000, stock: 22 }, { id: "5-700g", weight: "700g", price: 36000, stock: 15 }], tags: ["bestseller"], isFeatured: false, isBestseller: true, rating: 4.6, reviewCount: 67 },
  { id: "6", name: "Authentic Thuol Masii Karuvadu", nameTamil: "துல் மாசி கருவட", slug: "thuol-masi-karuvadu", description: "Elevate your coastal cooking with the intense, savory depth of our premium Thuol Masii. Sourced from the finest catch and prepared using traditional methods, our Thuol Masii (Maldivian-style dry fish) is the secret ingredient that transforms everyday meals into gourmet experiences. Whether you are crafting authentic Mas Huni, flavoring a spicy meen kulambu, or adding a rich, umami punch to your stir-fries and chutneys, this is the essential pantry staple for every seafood lover.\n\nWhy You'll Love It:\nAuthentic Traditional Flavor: Perfectly dried to lock in that deep, smoky, and concentrated fish essence that defines authentic coastal cuisine.\nPremium Quality: We take pride in our sourcing and hygiene, ensuring you receive only the cleanest, highest-grade dry fish.\nHighly Versatile: A tiny sprinkle goes a long way. Use it to enhance the depth of curries, salads, sambols, or traditional dry fish fry recipes.\nRich in Protein: A nutrient-dense, shelf-stable ingredient that adds a healthy protein boost to your diet.\n\nCulinary Tips:\nFor Curries: Lightly toast the Masii before adding it to your gravy to release an irresistible, smoky aroma.\nFor Sambols/Chutneys: Grind it with coconut, green chilies, and lime juice for a classic, tangy, and spicy side dish that pairs perfectly with hot rice or roti.\n\nNet Weight: 100g\nStorage: Keep in a cool, dry place. Reseal the pouch tightly after each use to maintain freshness and aroma.", shortDesc: "Maldivian-style dry fish - authentic & smoky", category: "Fish", images: ["http://10.0.2.2:4000/images/thuol-masi-1.jpg", "http://10.0.2.2:4000/images/thuol-masi-2.jpg", "http://10.0.2.2:4000/images/thuol-masi-3.jpg", "http://10.0.2.2:4000/images/thuol-masi-4.jpg"], skus: [{ id: "6-100g", weight: "100g", price: 11000, stock: 40 }, { id: "6-200g", weight: "200g", price: 20000, stock: 30 }, { id: "6-300g", weight: "300g", price: 29000, stock: 20 }, { id: "6-500g", weight: "500g", price: 47000, stock: 15 }], tags: ["premium"], isFeatured: false, isBestseller: false, rating: 4.9, reviewCount: 45 },
  { id: "7", name: "Rameswaram Premium Dried Prawns (Kaintha Iraal Karuvadu)", nameTamil: "கைந்த இறால் கருவட", slug: "kaintha-iraal-karuvadu", description: "Bring the rich, savory essence of the sea straight to your kitchen with our premium Kaintha Iraal Karuvadu. Sourced directly from small-boat fishers and sun-dried under strict hygienic conditions, our dried prawns retain the natural, robust flavor that defines traditional coastal cuisine.\n\nPacked with protein and free from artificial preservatives, our dried prawns are the perfect pantry staple for elevating your everyday cooking. Whether you are crafting a spicy Karuvaadu Thokku, adding depth to a fragrant sambar, or creating a crunchy stir-fry, these premium prawns offer unmatched quality in every bite.\n\nWhy Choose Our Dried Prawns?\n100% Natural: Pure, sun-dried goodness with no added chemicals or additives.\nSustainably Sourced: Directly procured from small-scale fishers to ensure freshness and support local livelihoods.\nHygienically Processed: Dried and packed in a strictly controlled environment for safety and superior quality.\nFlavor-Packed: Intense, umami-rich flavor that adds a signature 'seafood punch' to any dish.\nConvenient Packaging: Our resealable pouch keeps your prawns fresh, crisp, and ready for your next culinary adventure.\n\nCooking Suggestion: For best results, simply rinse under warm water before use to rehydrate and prepare the prawns for your favorite recipes.\n\nStorage Instructions: To maintain maximum freshness, keep this product in a cool, dry place away from direct sunlight. Once opened, store in an airtight container—or for longer-lasting quality, keep it in the refrigerator.", shortDesc: "Premium sun-dried prawns - authentic coastal flavor", category: "Prawns", images: ["http://10.0.2.2:4000/images/kaintha-iraal-1.png", "http://10.0.2.2:4000/images/kaintha-iraal-2.png", "http://10.0.2.2:4000/images/kaintha-iraal-3.png"], skus: [{ id: "7-90g", weight: "90g", price: 6500, stock: 35 }, { id: "7-180g", weight: "180g", price: 12000, stock: 28 }, { id: "7-270g", weight: "270g", price: 18000, stock: 20 }, { id: "7-550g", weight: "550g", price: 36000, stock: 12 }], tags: ["bestseller"], isFeatured: true, isBestseller: true, rating: 4.7, reviewCount: 92 },
  { id: "8", name: "The Ultimate Vanjiram Karuvadu", nameTamil: "வஞ்சிரம் கருவட", slug: "vanjiram-karuvadu", description: "Craving the perfect bite of Vanjiram? Our sun-dried, 100% natural Vanjiram Karuvadu is cleaned, processed, and packed with care to bring you the best of the ocean.\n\nWhy Choose Our Vanjiram?\n100% Natural: No chemicals, just fish and sea salt.\nSustainably Sourced: Fresh catch from small-scale coastal fishers.\nHygienically Packed: Sun-dried in a clean environment for superior flavor.\nPerfect for: Spicy fries, rich gravies, or a traditional coastal feast.\n\nProduct Highlights:\nFish Variety: Vanjiram (Seer Fish)\nProcessing: Sun-dried & hygienically cleaned\nIngredients: Fresh Fish, Sea Salt\nAdditives: None (100% Natural)\nStorage: Airtight container in a cool, dry place", shortDesc: "Premium sun-dried king fish - 100% natural", category: "Fish", images: ["http://10.0.2.2:4000/images/vanjiram-1.png", "http://10.0.2.2:4000/images/vanjiram-2.png"], skus: [{ id: "8-95g", weight: "95g", price: 6500, stock: 30 }, { id: "8-190g", weight: "190g", price: 12000, stock: 22 }, { id: "8-285g", weight: "285g", price: 18000, stock: 15 }, { id: "8-600g", weight: "600g", price: 36000, stock: 10 }], tags: ["premium"], isFeatured: false, isBestseller: false, rating: 4.8, reviewCount: 56 },
  { id: "9", name: "Premium Thundu Karuvadu", nameTamil: "துண்டு கருவட", slug: "thundu-karuvadu", description: "Bring the authentic, rustic flavors of the coast to your kitchen. Our Thundu Karuvadu is crafted for those who love the deep, savory, and umami-rich taste of traditional sun-dried fish but want the convenience of ready-to-cook pieces. Sourced directly from small-scale traditional boats, each piece is expertly cleaned and sun-dried under strict hygienic conditions to ensure you receive only the best quality.\n\nWhy You'll Love It:\nAuthentic Coastal Taste: We use a time-tested, 100% natural sun-drying process that locks in the rich, deep flavors that only real karuvadu can provide.\nZero Chemicals: Absolutely no additives or preservatives. Just pure, wholesome, dried fish cured with high-quality sea salt.\nReady-to-Cook Convenience: Say goodbye to the hassle of cleaning and cutting. Our 'Thundu' (chunk) cuts are perfectly portioned so you can drop them straight into your spicy karuvadu kuzhambu or fry them up for a crispy, flavorful side dish.\nNutrient-Dense: A powerhouse of protein and essential minerals, perfect for adding a boost of flavor and nutrition to your traditional meals.\n\nPerfect For:\nSpicy Fish Curry: The chunks hold their texture perfectly, absorbing all the spice and tang of your tamarind-based gravies.\nCrispy Fry: Toss them in a light coating of chili powder and curry leaves for a crunchy, addictive snack.\n\nChef's Tip: Before cooking, soak the pieces in lukewarm water for 10–15 minutes. This softens the texture and removes excess salt, ensuring every bite is perfectly seasoned!\n\nStorage Instructions:\nKeep your karuvadu at its best! Store in a cool, dry place away from direct sunlight. Once opened, we recommend keeping it in the refrigerator to maintain its signature freshness and aroma for longer.", shortDesc: "Salted dried fish chunks - ready to cook", category: "Fish", images: ["http://10.0.2.2:4000/images/thundu-3.png", "http://10.0.2.2:4000/images/thundu-1.png", "http://10.0.2.2:4000/images/thundu-2.png"], skus: [{ id: "9-120g", weight: "120g", price: 6500, stock: 40 }, { id: "9-240g", weight: "240g", price: 12000, stock: 30 }, { id: "9-360g", weight: "360g", price: 18000, stock: 20 }, { id: "9-700g", weight: "700g", price: 36000, stock: 12 }], tags: ["bestseller"], isFeatured: true, isBestseller: true, rating: 4.7, reviewCount: 88 }
];

app.post('/api/v1/auth/google', (req, res) => {
  const { token } = req.body;
  if (!token) return res.status(400).json({ success: false, message: 'Token required' });
  res.json({ success: true, data: { id: 'user-1', name: 'Test User', email: 'test@gmail.com', image: null, role: 'USER' } });
});

app.get('/api/v1/products', (req, res) => res.json({ success: true, data: products, total: products.length }));
app.get('/api/v1/products/shop', (req, res) => res.json({ success: true, data: products, total: products.length }));
app.get('/api/v1/products/featured', (req, res) => res.json({ success: true, data: products.filter(p => p.isFeatured) }));
app.get('/api/v1/products/bestsellers', (req, res) => res.json({ success: true, data: products.filter(p => p.isBestseller || p.isFeatured) }));
app.get('/api/v1/products/:slug', (req, res) => { const p = products.find(x => x.slug === req.params.slug); if (!p) return res.status(404).json({ success: false, message: 'Not found' }); res.json({ success: true, data: p }); });
app.get('/api/v1/categories', (req, res) => res.json({ success: true, data: [{id:'fish',name:'Fish',nameTamil:'மீன்'},{id:'prawns',name:'Prawns',nameTamil:'இறால்'}] }));
app.get('/api/v1/cart', (req, res) => res.json({ success: true, data: [] }));
app.get('/api/v1/orders', (req, res) => res.json({ success: true, data: [] }));
app.get('/api/v1/wishlist', (req, res) => res.json({ success: true, data: [] }));
app.get('/api/v1/addresses', (req, res) => res.json({ success: true, data: [] }));

const PORT = 4000;
app.listen(PORT, '0.0.0.0', () => console.log(`Backend running on port ${PORT} with ${products.length} products`));
